"use client";

import { useCallback, useState } from "react";
import { DualRateMetricCard } from "@/components/dashboard/dual-rate-metric-card";
import { MarketNotesPanel } from "@/components/dashboard/market-notes-panel";
import { MetricCard } from "@/components/dashboard/metric-card";
import { SectionHeading } from "@/components/dashboard/section-heading";
import { SiteToolsNav } from "@/components/ui/site-tools-nav";
import { backLinkClass, buttonPrimaryClass, buttonSecondaryClass } from "@/lib/design-tokens";
import type { DashboardBundle } from "@/lib/dfw-dashboard-sample-data";
import type { MarketNotesRecord } from "@/lib/market-notes/types";

function renderNationalMetric(
  m: DashboardBundle["national"][number],
  i: number,
) {
  if (m.chartKind === "dual-line") {
    return <DualRateMetricCard key={`nat-${i}-${m.title}`} metric={m} />;
  }
  return <MetricCard key={`nat-${i}-${m.title}`} metric={m} />;
}

type DfwMarketDashboardProps = {
  initialData: DashboardBundle;
  marketNotes: MarketNotesRecord | null;
};

export function DfwMarketDashboard({
  initialData,
  marketNotes,
}: DfwMarketDashboardProps) {
  const [data, setData] = useState(initialData);
  const [refreshKey, setRefreshKey] = useState(0);
  const [refreshing, setRefreshing] = useState(false);
  // NOTE: Market Notes are intentionally NOT regenerated by the client.
  // "Refresh Data" only re-fetches the dashboard metrics; the AI-written
  // notes update only on the monthly cron or a protected manual route.
  // The dashboard simply renders whatever was last saved in shared storage.

  const refresh = useCallback(async () => {
    const nextKey = refreshKey + 1;
    setRefreshing(true);
    try {
      const seed = nextKey * 2654435761;
      const res = await fetch(`/api/dashboard?seed=${seed}&refresh=1`, {
        cache: "no-store",
      });
      if (res.ok) {
        const bundle = (await res.json()) as DashboardBundle;
        setData(bundle);
        setRefreshKey(nextKey);
      }
    } catch (error) {
      console.error("[dashboard] Refresh failed", error);
    } finally {
      setRefreshing(false);
    }
  }, [refreshKey]);

  const nationalDual = data.national.filter((m) => m.chartKind === "dual-line");
  const nationalRest = data.national.filter((m) => m.chartKind !== "dual-line");

  const asOf = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const scrollToMarketSummary = (
    event: React.MouseEvent<HTMLAnchorElement>,
  ) => {
    event.preventDefault();
    document.getElementById("market-summary")?.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
    window.history.replaceState(null, "", "#market-summary");
  };

  return (
    <div className="min-h-full bg-[#f5f3ef] font-sans text-stone-800">
      <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-10 lg:px-8">
        <header className="border-b border-stone-200/80 pb-6 sm:pb-7">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
            <div className="min-w-0 space-y-2.5">
              <a href="https://harbaughrealestate.com" className={backLinkClass}>
                ← Back to Harbaugh Real Estate
              </a>
              <h1 className="text-balance font-sans text-3xl font-semibold tracking-tight text-stone-900 sm:text-4xl">
                Harbaugh DFW Market Dashboard
              </h1>
              <p className="max-w-2xl text-sm leading-relaxed text-stone-500 sm:text-base">
                A compact read on North Texas housing, mortgage markets, and the
                broader economy.
              </p>
            </div>
            <div className="flex shrink-0 flex-col items-start gap-3 sm:items-end">
              <p className="text-xs text-stone-400 tabular-nums">As of {asOf}</p>
              <div className="flex flex-wrap items-center gap-2">
                <a
                  href="#market-summary"
                  onClick={scrollToMarketSummary}
                  className={buttonSecondaryClass}
                >
                  Market Summary
                </a>
                <button
                  type="button"
                  onClick={() => void refresh()}
                  disabled={refreshing}
                  className={buttonPrimaryClass}
                >
                  {refreshing ? "Refreshing…" : "Refresh Data"}
                </button>
              </div>
            </div>
          </div>
          <div className="mt-5 sm:mt-6">
            <SiteToolsNav active="market-dashboard" />
          </div>
        </header>

        <main className="mt-10 space-y-12 sm:mt-12 sm:space-y-14">
          <section aria-labelledby="dfw-housing-heading">
            <SectionHeading
              eyebrow="Housing"
              title="DFW housing market"
              description="Metro-wide resale trends and pricing."
              id="dfw-housing-heading"
            />
            <div className="grid gap-3 sm:grid-cols-2">
              {data.dfw.map((m, i) => (
                <MetricCard key={`dfw-${i}-${m.title}`} metric={m} />
              ))}
            </div>
          </section>

          <section aria-labelledby="arl-mans-heading">
            <SectionHeading
              eyebrow="Local markets"
              title="Arlington & Mansfield housing market"
              description="Side-by-side read on Arlington and Mansfield markets"
              id="arl-mans-heading"
            />
            <div className="grid gap-3 sm:grid-cols-2">
              {data.arlington.map((m, i) => (
                <MetricCard key={`arl-${i}-${m.title}`} metric={m} />
              ))}
              {data.mansfield.map((m, i) => (
                <MetricCard key={`mans-${i}-${m.title}`} metric={m} />
              ))}
            </div>
          </section>

          <section aria-labelledby="national-heading">
            <SectionHeading
              eyebrow="Macro"
              title="National economy / rates"
              description="Rates, inflation, and national benchmarks that shape payment math."
              id="national-heading"
            />
            <div className="space-y-3">
              {nationalDual.map((m, i) => renderNationalMetric(m, i))}
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                {nationalRest.map((m, i) => renderNationalMetric(m, i + 100))}
              </div>
            </div>
          </section>

          <section aria-labelledby="regional-heading">
            <SectionHeading
              eyebrow="Regional"
              title="DFW / Texas economy"
              description="Texas and DFW labor and price conditions."
              id="regional-heading"
            />
            <div className="grid gap-3 sm:grid-cols-3">
              {data.regional.map((m, i) => (
                <MetricCard key={`reg-${i}-${m.title}`} metric={m} />
              ))}
            </div>
          </section>

          <section
            id="market-summary"
            aria-labelledby="notes-heading"
            className="scroll-mt-8"
          >
            <SectionHeading
              eyebrow="Narrative"
              title="Market Notes"
              description="Current observations and context for the latest market data."
              id="notes-heading"
            />
            <MarketNotesPanel notes={marketNotes} />
          </section>
        </main>

        <footer className="mt-14 border-t border-stone-200/80 pt-8 text-xs leading-relaxed text-stone-400">
          <p>
            Sources: Freddie Mac Primary Mortgage Market Survey, Federal Reserve
            Economic Data (FRED), S&P CoreLogic Case-Shiller, and the Texas Real
            Estate Research Center at Texas A&M University. Data may be
            preliminary, revised, seasonally adjusted, or reported on different
            update schedules depending on the source.
          </p>
          <p className="mt-8 text-center text-[0.7rem] tracking-wide text-stone-400">
            Copyright © {new Date().getFullYear()} Harbaugh Real Estate
          </p>
        </footer>
      </div>
    </div>
  );
}
